-- Task Table Schema
-- Module: Phase II - Module 1 (Database Setup)
-- Generated: 2026-01-16
--
-- This schema is generated by SQLModel's create_all() but documented here
-- for reference and manual verification in Neon console.

-- =============================================================================
-- TABLE: tasks
-- =============================================================================

CREATE TABLE IF NOT EXISTS tasks (
    -- Primary Key
    id SERIAL PRIMARY KEY,

    -- Foreign Key to users (Better Auth managed)
    -- Note: FK constraint will warn until users table exists (Module 3)
    user_id VARCHAR(255) NOT NULL,

    -- Task content
    title VARCHAR(200) NOT NULL,
    description TEXT,

    -- Task status
    completed BOOLEAN NOT NULL DEFAULT FALSE,

    -- Timestamps
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- INDEXES
-- =============================================================================

-- Index for user-specific queries (WHERE user_id = ?)
CREATE INDEX IF NOT EXISTS idx_tasks_user_id ON tasks(user_id);

-- Index for status-based queries (WHERE completed = ?)
CREATE INDEX IF NOT EXISTS idx_tasks_completed ON tasks(completed);

-- =============================================================================
-- CONSTRAINTS
-- =============================================================================

-- Title length constraint (1-200 characters)
ALTER TABLE tasks ADD CONSTRAINT IF NOT EXISTS check_title_length
    CHECK (char_length(title) >= 1 AND char_length(title) <= 200);

-- Description length constraint (max 1000 characters)
ALTER TABLE tasks ADD CONSTRAINT IF NOT EXISTS check_desc_length
    CHECK (description IS NULL OR char_length(description) <= 1000);

-- Foreign key constraint (added after users table exists in Module 3)
-- ALTER TABLE tasks ADD CONSTRAINT fk_tasks_user_id
--     FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- =============================================================================
-- NOTES
-- =============================================================================

-- 1. SQLModel generates this schema via metadata.create_all()
-- 2. The FK constraint is defined in the model but won't be enforced until
--    the users table is created by Better Auth in Module 3
-- 3. The updated_at column auto-update will be handled by ORM in Module 2,
--    not by database trigger (for simplicity)
-- 4. No migration system used - schema changes require manual intervention
-- 5. This file is for documentation; actual schema created by SQLModel

-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================

-- Check table exists
-- SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'tasks');

-- Check columns
-- SELECT column_name, data_type, is_nullable, column_default
-- FROM information_schema.columns WHERE table_name = 'tasks';

-- Check indexes
-- SELECT indexname, indexdef FROM pg_indexes WHERE tablename = 'tasks';

-- Check constraints
-- SELECT conname, contype, pg_get_constraintdef(oid)
-- FROM pg_constraint WHERE conrelid = 'tasks'::regclass;
